main: graver.erowtv.main.ErowTV
name: ErowTV
version: '2.0.0'
author: Richard Grave
description: ErowTV
api-version: 1.13
commands:
  test:
    description: Test command to check if commands are loaded
    usage: /test
  facing:
    description: Gives you your facing direction
    usage: /facing
  debug_messages:
    description: Turn debug messages on or off
    usage: /debug_messages